

spec_dept_sales = lm(Weekly_Sales ~ as.factor(IsHoliday) + Temperature + Fuel_Price + CPI + Unemployment + Size + as.factor(Dept), train[(train$Dept == 29) | (train$Dept == 30) | (train$Dept == 39) | (train$Dept == 43) | (train$Dept == 99) ,])

get_prediction_sales <- function(numb){

	sales = lm(Weekly_Sales ~ as.factor(IsHoliday) + Temperature + Fuel_Price + CPI + Unemployment + as.factor(Dept), train[train$Store == numb,])
	test[(test$Store == numb) & ( test$Dept%in%train[train$Store == numb,]$Dept ) , ]$Predict_Sales = predict(sales, test[(test$Store == numb) & ( test$Dept%in%train[train$Store == numb,]$Dept ) , ] )
	test[(test$Store == numb) & !( test$Dept%in%train[train$Store == numb,]$Dept ) , ]$Predict_Sales = predict(spec_dept_sales, test[(test$Store == numb) & !( test$Dept%in%train[train$Store == numb,]$Dept ) , ] )
	#pred = c(pred1,pred2)
	return(test)
}


	test = get_prediction_sales(1)
	test = get_prediction_sales(2)
	test = get_prediction_sales(3)
	test = get_prediction_sales(4)
	test = get_prediction_sales(5)
	test = get_prediction_sales(6)
	test = get_prediction_sales(7)
	test = get_prediction_sales(8)
	test = get_prediction_sales(9)
	test = get_prediction_sales(10)
	test = get_prediction_sales(11)
	test = get_prediction_sales(12)
	test = get_prediction_sales(13)
	test = get_prediction_sales(14)
	test = get_prediction_sales(15)
	test = get_prediction_sales(16)
	test = get_prediction_sales(17)
	test = get_prediction_sales(18)
	test = get_prediction_sales(19)
	test = get_prediction_sales(20)
	test = get_prediction_sales(21)
	test = get_prediction_sales(22)
	test = get_prediction_sales(23)
	test = get_prediction_sales(24)
	test = get_prediction_sales(25)
	test = get_prediction_sales(26)
	test = get_prediction_sales(27)
	test = get_prediction_sales(28)
	test = get_prediction_sales(29)
	test = get_prediction_sales(30)
	test = get_prediction_sales(31)
	test = get_prediction_sales(32)
	test = get_prediction_sales(33)
	test = get_prediction_sales(34)
	test = get_prediction_sales(35)
	test = get_prediction_sales(36)
	test = get_prediction_sales(37)
	test = get_prediction_sales(38)
	test = get_prediction_sales(39)
	test = get_prediction_sales(40)
	test = get_prediction_sales(41)
	test = get_prediction_sales(42)
	test = get_prediction_sales(43)
	test = get_prediction_sales(44)
	test = get_prediction_sales(45)

unique(train[train$Dept == 99,]$Store)